scenarios = [
	{
		//Crashed Airplane
		"scenario": "It was a calm evening when you stumbled upon a crashed airplane.",
		"reply1": "You find a secret compartment that contains some Coke. Seems like a win to me!",
		"answer1": "Search the insides",
		"damage1": 0,
		"reply2": "You try to power it up, but the badly damaged engine blows up. You die.",
		"answer2": "Try to power it up",
		"damage2": 100,
		"reply3": "It rained during the night, so I guess staying in the plane was worth it,",
		"answer3": "Use it as a bed",
		"damage3": 0,
	},
	{
		//Bob the Kitten
		"scenario": "After walking for 10 minutes you meet Bob the Kitten.",
		"reply1": "The kitten was quite angry at you for even mentioning milk. Apparently, he was a vegan and milk is a no go for him",
		"answer1": "Give him some milk ",
		"damage1": 0,
		"reply2": "You attacked, but he was ready. 20 other kittens jumped you and music started playing:<br>Everybody was kung fu fighting, (ooogh, aaagh).<br>Those CATS were fast as lightning (ooogh, aaagh).<br>It was very very frightening, (ooogh, aaagh).<br>but they fought with expert timing (ooogh, aaagh).",
		"answer2": "Try to kill him",
		"damage2": 60,
		"reply3": "Bob was quick, but the laser beam was quicker. He stopped and started crying for being the failure that he is.",
		"answer3": "Tease him with a cheap laser you bought a few days ago",
		"damage3": 0,
	},
	{
		//Bandit
		"scenario": "You were calmly walking until a bandit jumped you. You woke up tied up.",
		"reply1": "You started shouting for help. Lucky you, the bandit's name was Help. He got scared, thinking you are a magician and let you go.",
		"answer1": "Shout for help",
		"damage1": 0,
		"reply2": "You tried to flatter him, but the bandit was highly depressed and mistook your compliments as irony. He was so angry that he tried to end your life on the spot.",
		"answer2": "Try to flatter him",
		"damage2": 100,
		"reply3": "While you had a good idea, you didn't have marshmallows, so when he untied you hoping to have a nice evening, you broke his heart and ran away...",
		"answer3": "Invite him to burn some marshmallows above a bonfire and talk about the bandit's mental health problems",
		"damage3": 10,
	},
	{
		//Shooting Star
		"scenario": "You were traveling at night when a shooting star appeared.",
		"reply1": "While you were thinking of a wish the star fell down...<br>...on your head. The impact was so strong, that you died.",
		"answer1": "Stop and think of a wish",
		"damage1": 100,
		"reply2": "You were lucky, since 5 minutes after running you heard something very loud behind you. Oh? What's that? Is that not the sound of a meteorite? Well, you turned around and saw a huge bear, so now I can assure you that that, in fact, was not a flying rock. You played dead, although you almost didn't have to.",
		"answer2": "Run for your life in case it is a meteorite",
		"damage2": 50,
		"reply3": "Since you wanted to continue walking, that was exactly what you did. Hey, who said dreams couldn't be true!",
		"answer3": "Continue walking",
		"damage3": 0,
	},
	{
		//Frog
		"scenario": "It was a rainy day when you saw an abandoned wagon and decided to hide there for a bit. You found a frog there.",
		"reply1": "You kissed it and got poisoned. Such a surprise!",
		"answer1": "Kiss it",
		"damage1": 15,
		"reply2": "You eat it and die. Why? Because the frog was toxic would be my guess.",
		"answer2": "Eat it",
		"damage2": 100,
		"reply3": "The frog was very angry, but in the end it was just a frog, and couldn't do anything.",
		"answer3": "Throw out it of the wagon",
		"damage3": 0,
	},
	{
		//Sleep
		"scenario": "The sun is setting and you want to sleep.",
		"reply1": "You started sleeping on the tree, but you woke up on the ground.",
		"answer1": "Sleep in a tree",
		"damage1": 20,
		"reply2": "The waves choked you to death.",
		"answer2": "Sleep on a beach",
		"damage2": 100,
		"reply3": "Staying awake all night is usually not good for your health and sleep schedule and this time is no different.",
		"answer3": "Stay awake all night",
		"damage3": 20,
	},
	{
		//Abandoned House
		"scenario": "You find a strange, seemingly abandoned house.",
		"reply1": "You knock on the door, unfortunately wolves hear the knock and attack you. You are as alive as a dead person.",
		"answer1": "Knock on the door",
		"damage1": 100,
		"reply2": "The door is locked (for safety reasons probably).",
		"answer2": "Open the door and go inside",
		"damage2": 0,
		"reply3": "You didn't have guns and the best alternative was a kitchen knife, but you still managed to break the door. Inside you found some antidepressants. You can finally feel happy for an hour!",
		"answer3": "Run in guns blazing",
		"damage3": 0,
	},	
	{
		//Doll
		"scenario": "You find a doll on the road.",
		"reply1": "You take the doll. Congratulations! You now have a doll. With that dollish doll you can do a lot of stuff that people usually do with dollish dolls that are dolls.",
		"answer1": "Take it",
		"damage1": 0,
		"reply2": "You left it. It seems like it was a voodoo doll because 2 hours later your whole body started aching. Most likely somebody ran over it.",
		"answer2": "Leave it",
		"damage2": 60,
		"reply3": "Apparently the doll was linked with a trap. After you moved the doll a cloud of arrows came from the bushes and killed you.",
		"answer3": "Put it aside so no one runs over it",
		"damage3": 100,
	},	
	{
		//Antaniukas
		"scenario": "While walking you encounter Antaniukas - the car model hobbyist.",
		"reply1": "You start talking, he tells you his deepest desires. He talks so enthusiastically, he starts crying over the fact that he doesn't have a \"Ford Focus\".",
		"answer1": "Talk to him",
		"damage1": 0,
		"reply2": "He said that they died in a car accident. Apparently that was the reason he became a car collector.",
		"answer2": "Ask about his parents",
		"damage2": 10,
		"reply3": "He refused to take the toy and gave me an hour-long explanation between car models and car toys",
		"answer3": "Give him a toy car",
		"damage3": 5,
	},	
	{
		//Paulius the Tiger
		"scenario": "You were walking through a deep forest, when you met Paulius the Tiger.",
		"reply1": "You shout, he starts crying and runs back home. Was it worth it? Probably no, but now you can brag that you defeated a tiger.",
		"answer1": "Shout at him",
		"damage1": 0,
		"reply2": "You gave him some meat, sadly he eat not only the meat, but your arm too!",
		"answer2": "Feed him",
		"damage2": 50,
		"reply3": "Tigers understand the word \"Playing\" as biting and fighting, so this realy didn't end well for you.",
		"answer3": "Play with him",
		"damage3": 100,
	},
	{
		//Circus
		"scenario": "You were sleeping when you overheard festive music. After going to the source, you found a traveling circus.",
		"reply1": "After going to the popcorn stand you find out it's closed since it is midnight after all. The stand is painted in dazzling colors. If it wasn't next to a circus, it would really <i>pop</i> out.",
		"answer1": "Go to the popcorn stand",
		"damage1": 0,
		"reply2": "You go to the clown, but he doesn't respond. He just watches the sunset smiling with his freakish smile.",
		"answer2": "Talk to a clown",
		"damage2": 0,
		"reply3": "You go there and to stroke it. Sadly the zebra wasn't in a very good mood and kicked you so hard you died.",
		"answer3": "Inspect the zebra",
		"damage3": 100,
	},
	{
		//Stasiukas the Donkey
		"scenario": "While walking through a quite densely populated area you hear a donkey. A donkey who is screeching.",
		"reply1": "Apparently the donkey was stuck in a hole where one of the townspeople was going to be buried. After you help him, you investigate its tag. Apparently, he is the Stasiukas - the town mayor's personal donkey. Such a weird town this is...",
		"answer1": "Help it",
		"damage1": 0,
		"reply2": "While you were pleased with your finding, the town's guards weren't. Apparently, that wasn't an ordinary animal. He was Stasiukas - the town mayor's personal donkey. You tried to run, but the guard's arrows were faster than you. You died.",
		"answer2": "Take it for yourself",
		"damage2": 100,
		"reply3": "You put it inside, grab some popcorn, and watch the two battle it out. It's animal cruelty, but no one else sees it, so it's fine.",
		"answer3": "Put another donkey inside",
		"damage3": 20,
	},
	{
		//Poppy field
		"scenario": "Out of nowhere a poppy field appeared. It wouldn't be a problem if your path went around it. But no, it went straight through.",
		"reply1": "After 10 minutes of going through the flowers, you are safely back on the road. Now you even have some sleeping pills - poppies.",
		"answer1": "Go straight through",
		"damage1": 0,
		"reply2": "When walking you hear something behind the bushes (probably wolves). Oh no. OH NO. <b>OH FUCK!</b>.",
		"answer2": "Just walk around it",
		"damage2": 100,
		"reply3": "Apparently you started screaming like an idiot, you ran like one too. Atleast that is what the townsfolk told you after you woke up in a hospital. They didn't let you out for 2 days.",
		"answer3": "Have a mental breakdown",
		"damage3": 20,
	},
	{	
		//Sweet House
		"scenario": "While walking through a forest you find a rather sweet looking house. It may or may not be made out of candy.",
		"reply1": "The door opens and you meet a rather old black woman who can only say \"Sweetie\" for some reason. She gives you some cookies, and wishes you luck.",
		"answer1": "Knock on the door",
		"damage1": 0,
		"reply2": "You try to eat it, but it's wood. I know, such a surprise, such a plot twist. A house that isn't made out of candy? Outrageous! Why would anyone with a brain not make a house out of candy? Anyway, your mouth hurts now.",
		"answer2": "Try to eat the house",
		"damage2": 40,
		"reply3": "Ƭ̶͇̬̈́̑́̋̀̀̎̽́̾̓̔͒̌́̚̚н̴̢̨̙͙̞̹̯̘͈̠̼̣̹̩͚̖̩̰̠͕͍̦͂̆̀̿͋͊͑ͅɛ̴̨̢̛̪͖̬̩̰̰̠̯̻̟̙͓̹͉̒͐͛̑̐̉̽̾̊͊̐̇̐̀̓́̀̑́͒̈́̈́͋̈̔͆͆̿̽̓̿̎̕͝ ̶̧̞̩̫͕̰̠̮̣̮̱̞͍̆͗̈́͒̐͛̀̋͗̎̈́͆̋͌͐͒́͗̏̋̿̋̇͂̔͂̾͑͊͋̇̊̀̊͗͗͘̕͜͝ͅͅʌ̷̧̡̨̧̮̬̤͚̰̬̘͚͖̮̙͇̯̝̠̬̪͚̬͖̬̥̹̺̰̬̖̪͊̑͗͝ͅσ̴͕̻̬̜̪̠̤̫̥͎̠͖̲̗̞̟͉̞͙͚͇̺̩͈̝̯̖̦̌̿̈́̅͘͜͜͜͝ΐ̶̧̛̛̛̣͙̯͚̤̱̦͈̩͙͌͂̊́͌͗̑͆̎̀̆͌̒̍͋̈́̆͂̑́̓̅̅̒̕͘͘̚͝∂̸̡̢̛̬̳͚͔͇̹̝̰͕̰̣̣̯͈̝̭̲̗̦̬̰̤̼̿͌̆͒͑̔̋͒͋͊̋̿̈́́̒̅̈́̓̾͑͘͘̕͝ ̸̡̛̠̜͙̤̘̥̺̠̥̺͍͕̝̈́̽̈́̒̄̔̀̌̌̿̐͑̎̋̾̿̐͌̄̉̍̇̅͆̏́͐͐̎̌͛̕̕͝ͅc̷̢̧̢̨̖̬̲̲͓͙̟̳̝̜̯͉̦͓̰̯̝͈̰̬̰͍̯̰͎̜̎̅̈́͒̃̿͆̀́̾̔̂̆͛̇̚̕͝͠͠σ̸̢̡̡̛͍̱̹̲̟̰͍͔̝̻͚̳̖͉͆͐̆̿̊̇̔͌̏̍͊̈́͊͌́͂̀̃̓̂͂͐͒́͊̄͌̇͘͝͠͝и̷̜͖̫̹̠̫̗̭̫̔͊̄̈͂̈́͋̎̍̃̍͌̔ƨ̴̡̛̟̟̤̲̺͔̙͔̖̪̈́͛͊̅͛̂̉̔͊͌̈́͐̀̿̓͗̅̑̅͆̔̒̕̕͝͝͠͝ͅʋ̸̝̣̱̈̋͂̃͆̏́̔͑̊͑̔̆̓̉͗̅͐͂̃̀͗̄͂̎̉̽͒̋̄͂̀̃̕̚̕͝͝м̸̢̡̡̢̨͓̣̬̹̩͔̮̜̙̥̮̟̩̺̫̤̗͎̟̻̝̼͉̣̥̞͎̺̒͛̍͗̋͊̃̆͊̏̐ɛ̵̧̧̧̡̳̯̺͚̩̳͓͓̭̟̺̰̟̦͔̘̠̟̤̬̟̰͖̪͚͉̣͎̄̄̽͊͌̓͊̐̉̐͆͜͜ƨ̸̧̞̙̲̱̗̤̥̖̹̞͍͍̜̘̭̐̂̀̾̇̅͋͋̆̃̽́̃̌̿́̈́̐̇̑̄̄̐́͂͐͘͜ͅ ̴̢̟̮̳̗͕̫̖͍̪̻̳̦̯̭̳̲̥̝̌̔͑̅̎́̓̚ͅɛ̶̫̳̩͓̈́̉̓̈͋͊̉̆̉͗̓͗̈̌̿̓͑̀͆̓̂̓͋͑̏́̈́̅̐̀͝͝͠ʌ̵̳̟̘̼͈̠̥͑̐̄̊̓̄̐̈́͗͆̊͛̔ɛ̸̢̧̧̙̳̺̟͉̠̺̗̩̻̣͓̗̺̟̮̜̰̰̓̌̂̈̂̍̍͑̊̍̓͑̋̒̄̈́̂̇͌̃̏̑͌͌̔͘͘̚͜͜͝͝ͅя̸̛̛̛͍̥̱̖̻̻̹̹̤̬̭̺͇̤͈̯̤͕͕͈̥̰̅̎͌̆͐͐̏̆̅͑̉͂̏̐̄͋͑̿͑̿͆̎̃̒͒̓̑̓͒̊͌͘͝ͅʏ̴̢̥̬͙̪͓̙̻͎̰̜̄̉̐̊̀̊̽̒̾̽̈̋͋͗̇͛̅̕͠т̴̝̯͇͔̬͖̐̉̉͛̐̉̑͛̌̚̚͠н̵̧̨̨͖͈͓̬̳͉̳͈̯̟͓̻̞̹̜̟͍̤̯̱̜̣͓̞͔͕͍̜̬̪̍̋̒̇̈́̔͐͐̽̀̉ͅι̶̳̐̀̒̈́̿̈͗͑͂͊̄̎͂̀̌̓́̍̍͒̾̑̀̏̒̈́̏̓̐̃͘͘̕͠и̴̧̧̡̛̯̺̬̻̰̖̮̇̌͑͐̎͐̾̒̓̓̐͑͋͘͘̕͜͝͝ɢ̶̧̛̛̩̙̜͔̀̈̏̉̀͗͐̀͐̀̈́͗̑͆́̀͐̎͑͒̈́͛̒͆̿̂̂͑́͗̌̇̑͜͠",
		"answer3": "Summon a black hole to remove this house from the face of the earth",
		"damage3": 666,
	},
	{	
		//Jonas the coke addict
		"scenario": "You find a house with a rather interesting inhabitant. That's right! It's Jonas - the soda addict!",
		"reply1": "He chugs the bottle in one big gulp and doesn't even taste the difference. He even asks for more...",
		"answer1": "Give him a soda bottle filled with dirty water",
		"damage1": 0,
		"reply2": "He takes the bottles like a brain dead child and happily drinks them. While drinking he tells you he may or may not have diabetes. Oh, and you really don't want to mix diabetes and a lot of sugar...<br>And... He's dead. Welp gotta leave before anyone finds you.",
		"answer2": "Give him more soda",
		"damage2": 0,
		"reply3": "After talking with him for 5 minutes you are sure that he is a <i>noob</i>, who doesn't even know he's a noob who doesn't even know all the chemical compounds inside the most popular modern-day fizzy drinks.",
		"answer3": "Talk with him about soda",
		"damage3": 0,
	},
	{
		//GPS
		"scenario": "In the middle of the road you find a GPS that somebody lost",
		"reply1": "You leave it. It is not like anyone needs that <em>boomer</em> trash anymore...",
		"answer1": "Leave it",
		"damage1": 0,
		"reply2": "You try to turn this ancient machine on, but it doesn't respond. Of course even if it had some power inside, it wouldn't be of any use to you.",
		"answer2": "See if it's working",
		"damage2": 0,
		"reply3": "After an hour you find a GPS collector who needs help. You give him your findings, but he decided that you stole it from him. You got hit so hard your soul escaped the body.",
		"answer3": "Take it just because",
		"damage3": 100
	},
	{
		//Lettuce Tower
		"scenario": "While walking through a very very deep forest you find the fabled lettuce tower. It is basically a giant lettuce. People say that you could feed an entire family for a month with this thing",
		"reply1": "You can't. I mean what did you expect? It is a giant tower, bigger than you, and you wanted to take it... The nerve of some people.",
		"answer1": "Take it with you",
		"damage1": 10,
		"reply2": "The problem is that there are no families nearby. It is black death's fault, not mine.",
		"answer2": "Feed a family",
		"damage2": 0,
		"reply3": "You try to eat it, but it isn't that tasty. In fact you feel a bit dizzy. That is what happens when plants pick quantity over quality.",
		"answer3": "Eat it",
		"damage3": 50,
	},
	{
		//Merchant
		"scenario": "A weird looking marchant passes by.",
		"reply1": "Apparently he is selling some old school technology called \"GPS\".",
		"answer1": "Catch up to him and ask what is he selling",
		"damage1": 0,
		"reply2": "You catch up to him and try to sell your stuff. He angrily replies saying that he is a merchant, not a trash bin for stuff travellers no longer need.",
		"answer2": "Catch up to him and try to sell hare meat you found 10 minutes ago.",
		"damage2": 0,
		"reply3": "You ignored him.",
		"answer3": "Ignore him",
		"damage3": 0,
	}
];